import './globals.css'
import type { Metadata } from 'next'
import { Bellefair } from 'next/font/google'

const bellefair = Bellefair({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Carousel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
        />
      </head>
      <body className={bellefair.className}>
        {children}
      </body>
    </html>
  )
}
